In [ ]:
import pandas as pd

restaurants = pd.read_csv('restaurants.csv')
restaurants.head()

<ipython-input-16-7cedcb8759d8>:3: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  restaurants = pd.read_csv('restaurants.csv')

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,GoodForDancing,BestNights,BYOB,Corkage,BYOBCorkage,AcceptsInsurance,RestaurantsCounterService,Open24Hours,AgesAllowed,DietaryRestrictions
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UJsufbvfyfONHeWdvAHKjA,Marshalls,21705 Village Lakes Sc Dr,Land O' Lakes,FL,34639,28.190459,-82.457380,3.5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
restaurants_phili = restaurants[restaurants['city'] == 'Philadelphia']
restaurants_phili = restaurants[['name','business_id','categories','address','stars']]
print(restaurants_phili)

                                        name             business_id  \
0                         St Honore Pastries  MTSW4McQd7CbVtyjqoe9mw
1                   Perkiomen Valley Brewery  mWMc6_wTdE0EUBKIGXDVfA
2                             Sonic Drive-In  CF33F8-E6oudUQ46HnavjQ
3                             Sonic Drive-In  bBDDEgkFA1Otx9Lfe7BZUQ
4                                  Marshalls  UJsufbvfyfONHeWdvAHKjA
...                                      ...                     ...
53047                      Dutch Bros Coffee  cM6V90ExQD6KMSU3rRB5ZA
53048                   Savaya Coffee Market  1jx1sfgjgVg0nM6n3p0xWA
53049  La Quinta by Wyndham NW Tucson Marana  qQ7FHvkGEMqoPKKXPk4gjA
53050          Adelita Taqueria & Restaurant  WnT9NIzQgLlILjPT0kEcsQ
53051                           The Plum Pit  2O2K6SXPWv56amqxCECd4w

                                              categories  \
0      Restaurants, Food, Bubble Tea, Coffee & Tea, B...
1                              Brewpubs, Breweries, Food
2      Burgers, Fast Food, Sandwiches, Food, Ice Crea...
3      Ice Cream & Frozen Yogurt, Fast Food, Burgers,...
4                   Department Stores, Shopping, Fashion
...                                                  ...
53047  Cafes, Juice Bars & Smoothies, Coffee & Tea, R...
53048  Specialty Food, Food, Coffee & Tea, Coffee Roa...
53049  Hotels & Travel, Hotels, Event Planning & Serv...
53050                               Restaurants, Mexican
53051  Restaurants, Comfort Food, Food, Food Trucks, ...

                         address  stars
0                    935 Race St    4.0
1                  101 Walnut St    4.5
2                  615 S Main St    2.0
3            2312 Dickerson Pike    1.5
4      21705 Village Lakes Sc Dr    3.5
...                          ...    ...
53047        1181 N Milwaukee St    4.0
53048          11177 N Oracle Rd    4.5
53049   6020 West Hospitality Rd    2.5
53050              1108 S 9th St    4.5
53051            4405 Pennell Rd    4.5

[53052 rows x 5 columns]

In [ ]:
restaurants_phili['categories'] = restaurants_phili['categories'].apply(lambda x: [s.strip() for s in x.split(',')])

<ipython-input-18-5c6db1c06357>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurants_phili['categories'] = restaurants_phili['categories'].apply(lambda x: [s.strip() for s in x.split(',')])

In [ ]:
print(restaurants_phili.iloc[0]['categories'])

['Restaurants', 'Food', 'Bubble Tea', 'Coffee & Tea', 'Bakeries']

In [ ]:
# new_features file contains mapping of 256 features to a smaller subset based on groupings

feature_map = pd.read_csv('new_features.csv')
feature_map['Feature'] = feature_map['Feature'].str.replace("',", "")
feature_map.head()

                     Feature value1  value2  value3
0             Beverage Store   drop     NaN     NaN
1          Department Stores   drop     NaN     NaN
2                 Smokehouse      2     NaN     NaN
3             Valet Services      3     NaN     NaN
4  Ice Cream & Frozen Yogurt      4     NaN     NaN

In [ ]:
feature_map.head()

feature_map = feature_map[feature_map['value1'] != 'drop']
feature_map = feature_map[feature_map['value1'] != 'drop?']
feature_map = feature_map.dropna(subset=['value1'])


feature_map['value1'] = feature_map['value1'].astype(int)

In [ ]:
# we grouped some more features together so next few blocks of code are grouping 28 and 17 together, 6 and 25, and 14 and 7
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] == 28:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = 17

In [ ]:

for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] == 25:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = 6

In [ ]:
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] == 14:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = 7

In [ ]:
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] > 28:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = feature_map.iloc[i, feature_map.columns.get_loc('value1')] - 1

In [ ]:
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] > 25:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = feature_map.iloc[i, feature_map.columns.get_loc('value1')] - 1

In [ ]:
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value1'] > 14:
        feature_map.iloc[i, feature_map.columns.get_loc('value1')] = feature_map.iloc[i, feature_map.columns.get_loc('value1')] - 1

In [ ]:
for i in range(len(feature_map)):
    if feature_map.iloc[i]['value2'] > 28:
        feature_map.iloc[i, feature_map.columns.get_loc('value2')] = feature_map.iloc[i, feature_map.columns.get_loc('value2')] - 3

In [ ]:
feature_mapping = {}
for i in range(len(feature_map)):
  vals = []
  if not pd.isna(feature_map.iloc[i]['value1']) and feature_map.iloc[i]['value1']!="drop" and feature_map.iloc[i]['value1']!="drop?":
    vals.append(feature_map.iloc[i]['value1'])
  if not pd.isna(feature_map.iloc[i]['value2']):
    vals.append(feature_map.iloc[i]['value2'])
  if not pd.isna (feature_map.iloc[i]['value3']):
    vals.append(feature_map.iloc[i]['value3'])

  feature_mapping[feature_map.iloc[i]['Feature']] = vals

In [ ]:
print(feature_mapping)

{'Smokehouse': [2], 'Valet Services': [3], 'Ice Cream & Frozen Yogurt': [4], 'Delis': [5], 'Beer Bar': [1], 'Sushi Bars': [6], 'Diners': [7], 'Indian': [8], 'Salad': [9], 'Southern': [10], 'Pasta Shops': [11], 'Patisserie/Cake Shop': [12], 'Pakistani': [8], 'Scandinavian': [13], 'American (Traditional)': [7], 'Fondue': [14], 'Gluten-Free': [15], 'Candy Stores': [4], 'Nightlife': [16], 'Taiwanese': [17], 'Food Trucks': [18], 'Greek': [19], 'Cocktail Bars': [1], 'Burgers': [7], 'Donairs': [20], 'Tex-Mex': [21], 'Guamanian': [22], 'Latin American': [21], 'Eastern European': [23], 'Japanese Curry': [6], 'Poutineries': [24], 'Canadian (New)': [24], 'Steakhouses': [7], 'Noodles': [8], 'Themed Cafes': [12], 'Uzbek': [8], 'Breakfast & Brunch': [25], 'Mongolian': [8], 'Shanghainese': [8], 'Drive-In Theater': [34], 'Cambodian': [8], 'Delicatessen': [5], 'Wineries': [16], 'Spanish': [27], 'Speakeasies': [1], 'Meaderies': [1], 'Turkish': [20], 'Comfort Food': [28], 'Whiskey Bars': [1], 'Dance Clubs': [16], 'Vegetarian': [29], 'Live/Raw Food': [30], 'Tacos': [21], 'Afghan': [8], 'Sandwiches': [5], 'Coffeeshops': [12], 'Hungarian': [31], 'Persian/Iranian': [8], 'Japanese': [6], 'Szechuan': [8], 'American (New)': [7], 'Pita': [20], 'Brazilian': [32], 'Custom Cakes': [12], 'Buffets': [33], 'Cabaret': [34], 'Bagels': [12], 'Bowling': [34], 'Sri Lankan': [8], 'Bakeries': [12], 'Belgian': [31], 'Peruvian': [23], 'Breweries': [1], 'Bars': [1], 'Coffee Roasteries': [12], 'Pubs': [1], 'Conveyor Belt Sushi': [6], 'Wraps': [5], 'Malaysian': [8], 'Syrian': [20], 'Ethiopian': [8], 'Calabrian': [26], 'Italian': [16], 'Cucina campana': [26], 'Puerto Rican': [27], 'New Mexican Cuisine': [21], 'Beer Gardens': [1], 'Wine Tasting Room': [1], 'Pan Asian': [8], 'Cuban': [27], 'Colombian': [37], 'Venezuelan': [37], 'Chicken Wings': [7], 'Himalayan/Nepalese': [8], 'Donuts': [12], 'Karaoke': [16], 'Fast Food': [5], 'Ukrainian': [35], 'Senegalese': [36], 'Donburi': [6], 'Somali': [36], 'Burmese': [8], 'Juice Bars & Smoothies': [46], 'Vietnamese': [8], 'Mediterranean': [20], 'Hawaiian': [37], 'South African': [36], 'Hakka': [8], 'Modern European': [38], 'Creperies': [4], 'Moroccan': [20], 'Egyptian': [20], 'Coffee & Tea': [12], 'Izakaya': [6, 1.0], 'Tapas/Small Plates': [27], 'Tapas Bars': [27, 1.0], 'Bartenders': [1], 'Serbo Croatian': [31], 'Iberian': [27], 'Sicilian': [26], 'Acai Bowls': [32], 'Chinese': [8], 'Scottish': [24], 'Middle Eastern': [20], 'Caribbean': [36], 'Bistros': [39], 'Pizza': [26], 'Arabic': [20], 'Hot Dogs': [7], 'Fish & Chips': [24], 'Drive-Thru Bars': [1], 'African': [36], 'Asian Fusion': [8], 'Thai': [8], 'Wine Bars': [1], 'Ramen': [8], 'Brasseries': [39], 'Russian': [35], 'Irish Pub': [24, 1.0], 'Vegan': [40], 'Tonkatsu': [6], 'Hot Pot': [8], 'Georgian': [41], 'Cafeteria': [12], 'Cajun/Creole': [42], 'Desserts': [4], 'Bubble Tea': [12], 'Wine & Spirits': [1], 'Bangladeshi': [8], 'Cupcakes': [12], 'Cafes': [12], 'Dominican': [27], 'Austrian': [31], 'Cheesesteaks': [7], 'Gelato': [4], 'Mexican': [21], 'Haitian': [36], 'Halal': [8], 'Portuguese': [27], 'Irish': [24], 'Salvadoran': [21], 'Seafood': [43], 'Trinidadian': [36], 'Dim Sum': [8], 'French': [39], 'Tuscan': [26], 'Teppanyaki': [6], 'British': [24], 'Kebab': [20], 'Korean': [6], 'Hainan': [8], 'Laotian': [8], 'Polish': [31], 'Czech': [31], 'Pop-Up Restaurants': [34], 'Singaporean': [8], 'Tiki Bars': [37, 34.0], 'Soul Food': [20], 'Armenian': [41], 'Dinner Theater': [34], 'Hookah Bars': [1], 'Hong Kong Style Cafe': [8], 'Sardinian': [26], 'Local Flavor': [45], 'Waffles': [4], 'Pancakes': [4], 'Israeli': [20], 'Pretzels': [12], 'Cantonese': [8], 'Falafel': [20], 'Empanadas': [27], 'Champagne Bars': [1], 'German': [31], 'Indonesian': [8], 'Barbeque': [44], 'Honduran': [21], "Dumplings'": [8]}

In [ ]:
cols = ['ID','Restaurant']
for i in range (1,47):
  cols.append(i)

updated_restaurants = pd.DataFrame(columns=cols)

for i in range(len(restaurants_phili)):
  row = restaurants_phili.iloc[i]
  categs = row['categories']
  counts = {}
  new_row = []
  new_row.append(row['business_id'])
  restaurant_name = row['name']
  for value in categs:
    if not pd.isna(value):
      if value in feature_mapping:
        new_val = feature_mapping[value]
        #print(new_val)
        for v in new_val:
          counts[int(v)]=1
  new_row.append(restaurant_name)
  for j in range(1,47):
    if j in counts:
      new_row.append(counts[j])
    else:
      new_row.append(0)
  updated_restaurants.loc[i]=new_row

In [ ]:
updated_restaurants.head()
updated_restaurants.to_csv('restaurants_new.csv', index=False)